version: '2.3'
services:
  gtracker:
    build: .
    ports:
      - "5000:80"
    depends_on:
      database:
        condition: service_healthy
  database:
    build: 
      context: .
      dockerfile: Database.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
      - MYSQL_USER=sbdb
      - MYSQL_PASSWORD=foobar
      - MYSQL_DATABASE=gtracker_db   
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10