version: '3'
services:
  gtracker:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - database
  database:
    build: 
      context: .
      dockerfile: Database.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
      - MYSQL_USER=sbdb
      - MYSQL_PASSWORD=foobar
      - MYSQL_DATABASE=gtracker-db   
    ports:
      - "3306:3306"